---
title: Happily Ever After
date: 2023-12-12 13:41:22
categories:
  - podcast
  - happiness-lab
---

I came across a very interesting idea on a [Happiness Lab adjacent podcast](https://www.hhs.gov/surgeongeneral/priorities/house-calls/dr-laurie-santos-encore/index.html)

Thanks to Disney fairy tales, or perhaps even before Disney, the phrase "happily ever after" has become commonplace in our society. This phrase seems to suggest that there is a "final state of happiness" which is the goal of life, and once achieved, life remains that way. 

This might sound benign, and at best, like a concept for children. However, it's very possible that the phrase has become ingrained in our collective psyche without us realizing it. Subconsciously, we may find ourselves striving to achieve this elusive goal in life.

The central teaching of Buddhism, which is essentially common sense, states that life is defined by change. No state is permanent, except death. Desiring and pursuing something impermanent is the cause of human suffering. 

I find it fascinating that we might have created this illusory goal for ourselves without intending any harm, yet now we are suffering the consequences of this delusion.

