---
title: Severance 
date: 2023-12-12 09:28:43
categories:
  - series
  - podcast
  - dystopia
  - sci-fi
  - very-bad-wizards
---

I saw *Severance* a while back when it was released but was reminded of it by a [brilliant episode of Very Bad Wizards](https://verybadwizards.com/episode/episode-236-your-outie-is-skilled-at-lovemaking-with-paul-bloom).

I enjoy reading and watching sci-fi dystopian worlds. It is one of my favorite genres, one that sci-fi explores particularly well. However, rarely do any of these stories get under my skin. Even the deeply poignant ones with no redemptive qualities, like *Blade Runner*, never perturbed me. I was moved by it emotionally and might have shed a tear at the final scene, but I was feeling things from a distance.

With *Severance*, though, I felt viscerally disturbed. Even just thinking about it makes me squirm in my chair. It is somewhat reminiscent of *1984*. I can feel myself being a part of this world. I feel all the frustration and absurdity that the characters experience. I understand their coping mechanisms.

The dark humor of the series makes it more palatable for me than *1984*. But it is still a hard watch. It is one of my favorite series, and yet I shudder at the thought of watching it again. I know that I will watch the second season when it comes out, but it will be with a mix of awe and anxiety.

Finally, the most disturbing aspects of both *Severance* and *1984* are the abject helplessness and the utter lack of hope. You can just feel the unfairness of the world trampling upon everyone, and none of the characters have any chance of escaping. Because *Severance* is aimed at the ever-optimistic American audience, I just know that in the second season the "small guys" are going to win. But if this series were to stay honest and live up to its true potential, they shouldn't. This series should follow the same unyielding path as *1984*. Some stories do need to end in a tragedy.
