---
title: Blue Eye Samurai
date: 2023-12-26 22:44:20
categories:
  - series
  - anime
  - japanese
  - netflix
---

Netflix has created a masterpiece with Blue Eye Samurai. 

There are some standard tropes - lonely samurai, mad skilled, dark past, revenge/mercenary for hire, amateur and naive apprentice, etc.
A female protagonist with non-japanese ancestry adds a bit of novelty but not sufficient enough and the first couple of episodes feel pretty standard.

But then as the characters develop and the backstory is revealed, the show really takes off. 
I distinctly remember watching S1E5 - The Ronin and the Bride - and unable to contain myself with excitement. 
There is a play in the episode - a story within a story - that is used to reveal Mizo's past. 
This is sheer genius. They could have just shown her backstory and the episode would still have been good. 
But this incorporation of a Japanese myth being told as a play which then parallels Mizu's life makes this episode great.

Another great thing about this show is that it not emotionless, stoic, cool as many samurai shows tend to be. Sure Mizu is cold-hearted at times but the show has a warmth and gritty authenticity that is very rare. 
The ending of S1E5, for example, is heart wrenching. If you did not shed a tear or get goosebumps watching this episode, you are a psychopath.

<iframe width="560" height="315" src="https://www.youtube.com/embed/GNBBpCwAPK4?si=hdXDTk-NvE9eeSwA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>