project:
  type: website
  output-dir: docs

website:
  title: "Journal"
  navbar:
    left:
      - text: Hobbies
        href: posts/hobbies/
      - text: Philosophy
        href: posts/philosophy/
      - text: Travel
        href: posts/travel/
      - text: Uncategorized
        href: posts/uncategorized/
    right:
      - icon: github
        href: https://github.com/apurvanakade/journal/
        aria-label: GitHub
  # sidebar: 
  #   style: floating
  #   search: true
  #   contents: auto
  open-graph: true
  site-url: https://apurvanakade.github.io/journal/
  repo-url: https://github.com/apurvanakade/journal/
  search:
    type: overlay
    location: navbar
  

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css

output-dir: docs