---
title: Journal

listing:
  fields: [date, title, description, categories, author]
  sort: "date desc"
  contents: "posts/**/*.qmd"
  sort-ui: false
  filter-ui: false
  categories: true
  feed: true
page-layout: full
---

I've been blogging for as long as I can remember, starting from the early days of Blogger, Wordpress, and Tumblr, to the newer self-hosted realms of Github, Jekyll, and Hugo. Now in the new phase of my life at JHU, here I am once again starting to write again. I plan to write about the topics that currently occupy my thoughts: math, <s>teaching</s> learning, Lean, programming, meditation, philosophy of mind, books, movies, and more...

For me, writing serves as a way to clarify my thoughts while staying honest and consistent. 
Feynman once said "*The first principle is not to fool yourself – and you are the easiest person to fool.*" 
Expressing your thoughts and putting them out in the world (for nobody to read) is the first step towards that.
<!-- 
The title of this post is a meditation prompt by Sam Harris.
I'm serious about practicing meditation and mindfulness, but regrettably, not very good at it. 
Whenever I catch myself doing something I would rather not (like procrastinating writing), I just remind myself to *Begin Again*. -->

So here's to not fooling yourself and to new beginnings. 
