---
title: Hollow Knight
date: 2023-11-05 13:38:51
categories:
  - challenging
  - artsy
  - beautiful
  - video-game
---

Hollow Knight is one of the best video games I've ever played. I used to play a lot of games during my school and college days but took a break during grad school. I recently resumed playing video games and stumbled upon Hollow Knight by chance.

I began the game unenthusiastically, assuming it would be about a cute little bug navigating Hallownest. I was completely mistaken. This is one of the most brutal and challenging games ever made. The realization hits when you face your first boss. The game shifts from casual to intense in an instant.

What sets this game apart – aside from the gameplay, music, ambiance, themes, lore, story, graphics, essentially everything – is the uncompromising attitude of the designers. The boss fights are insanely challenging, but they are manageable with enough practice. You need to grind, observe, and learn all the boss moves before even thinking of attacking them.

As you delve deeper into the game, the challenge extends beyond the boss fights. The late-game levels, like DeepNest, are tough and require significant effort to clear.

Furthermore, the game lacks manuals or instructions. You learn by doing. Even the maps are initially hidden, encouraging you to explore and learn Hallownest through exploration.

Now that the game is popular, the genius of Team Cherry, its creators, is evident. Their vision and commitment are unparalleled. But I wonder about their thought process during development. They must have received feedback about the difficulty of some bosses or the need for easier navigation, yet they remained true to their convictions. They trusted that players would possess the grit and enthusiasm to keep grinding and learning, a testament to their faith in people and their game’s ability to engage players.

---

Outside gaming, Hollow Knight has impacted my life significantly.

1. It has made me more optimistic about humanity. Watching countless speedruns and meme runs on YouTube, I’m constantly aware of my skill level. Seeing the heights people can reach with dedicated practice is humbling and amazing. It shows our great capacity for learning and adapting.

2. It has made me realize my love for challenges. Despite the stress and difficulty of clearing hard levels and boss fights, the satisfaction at the end is immense. There are bosses and levels I may never clear, but I enjoy improving with each attempt. It’s a wonderful metaphor for life.

3. Surprisingly, it has also influenced my teaching. My courses are challenging, and my exams are generally tough. I used to feel guilty and considered toning it down, but not anymore. I don’t mind the difficulty of my courses or exams, as long as they provide students with ample opportunity to practice, learn, and grow. Some students may excel and do ‘speedruns’, while others might struggle with harder levels – and that’s okay. The joy lies in the process, not the destination.