---
title: Hollow Knight
date: 2023-11-05 13:38:51
categories:
  - video game
  - attitude
---

Hollow Knight is one of the best video games I've ever played. I used to played a lot of games when I was in school and college but then took a break during my grad school.
I recently started playing video games again and happened to accidentally run into Hollow Knight. 

I started the game unenthusiatically, thinking that it was going to be a game about a cute little bug navigating Hollownest. I could not have been more wrong. This is one of the most brutal and challenging games ever made. You start realizing this when you encounter your first boss. The game goes from being casual to being intense within the blink of an eye. 

However what makes this game so unique - other than the gameplay, the music, the ambience, the themes, the lore, the story, the graphics, basically everything - is the uncomprising attitude of the game designers. The boss fights in the game are insanely challenging. BUT they are all manageable with enough practice. And practice you do need. You have to grind and grind and observe and learn all the boss moves before you can even think of attacking them. 

Once you get deep into the game, this extends to far beyond the boss fights. The late game levels are themselves quite challenging and require you to put in quite a bit of effort to clear - I'm talking about you DeepNest. 

On top of this, there are no manuals or instructions anywhere in the game. You learn everything by doing. Even the maps are hidden at first and you're expected to explore and learn Hollownest by exploring it.

Now that this game is so big, the genius of Team Cherry, its creators is obvious. Their vision and commitment to it is second to none. But I wonder what their thinking process must have been while making the game. Surely they must have received feedback that some of the bosses are too difficult or that they need to make some of the levels easier to navigate otherwise gamers would lose interest. But they stuck with their convictions. They somehow trusted that the people who would play their game would have enough grit and enthusiasm to keep grinding and keep learning. This requires a great amount of faith in people and also in your own game's ability to keep the gamers engaged. 


---

However, this game has had a bigger impact on my life outside of just gaming.

1. It has made me a little more optimistic about humanity. I've watched countless Hollow Knight speed runs and meme runs on YouTube now and amd constantly aware of how bad I still am at this game. But when I see the skill levels people can attain after hours of dedicated practice I feel deeply humbled and amazed. We truly are great at learning and adapting.

2. It has made me realize that I love doing hard things. Even though clearing the hard levels and the difficult boss fights is extremely stressful and challenging, it is also greatly satisfying. The pleasure at the end of the ordeal is indescribable. There are several bosses and levels in the game that I still have not cleared and I probably never will, but that no longer matters. I love just playing those fights over and over and get a little better at them every single time. What a great metaphor for life!

3. The third effect surprised me completely. This game has also affected the way I teach. My courses tend to be on the difficult side. I give students a lot of work and expect a lot from them. My exams are challenging in general and are usually a struggle. I used to feel a bit guilty about this and tried to tone myself down but I no longer feel this way. I no longer mind that my courses are hard and that my exams are challenging - as long as I'm giving students enough opportunity to practice and learn and grow it's all worth it. Some of my students will become extremely skilled and do speed runs, but others, like me, would never be able to clear some of the harder levels. And that's ok. The joy is in the process and not the destination.