---
title: Candles
date: 2024-06-09
categories:
  - memories
  - india
  - nostalgia
---

I was driving north on Greenmount and noticed that the traffic lights at many intersections had stopped working. "Typical Baltimore," was my first thought. Thankfully, it was Sunday morning, and the streets were empty, so it wasn't too bad. If anything, I was pleasantly surprised to see everyone being civil and patiently waiting for others at the defunct lights. My destination turned out to be devoid of electricity as well. A tree had fallen nearby, taking down some electric wires with it. We sat in darkness, barely shielded from the sweltering heat outside.

It made me think of the power outages we used to have in India when I was a child. Every summer, before the monsoon blessed the land, the rivers would run dry, and so would the supply of electricity. Every Wednesday, or was it Thursday, the coolers would shut themselves off, and we found ourselves sitting in the verandas, fruitlessly fanning ourselves with makeshift handheld fans.

Sometimes the outages were planned, but often they came as a surprise, in the dark of the night. All of us kids would scream at the top of our voices, partly from surprise and partly from joy; we couldn't possibly do our homework in darkness, could we? It feels surprising now to think of how casually we took it. There were no deadlines to meet, no hurry to get anything done. We'd make impatient calls to MSEB but mostly took life as it came. This was a time to catch up with neighbors we hadn't chatted with in a while. Did I ever look up at the stars? I don't remember. I do remember the bats, scary and fascinating, swooping over our heads in the darkness. And the mosquitoes.

A narrow, crooked white candle would emerge from one of the many drawers whose contents were only privy to grandmothers. Light the candle with the cheap matchsticks, tilt it over to let the wax drip, plant the candle on the table. It barely lit a single room, and yet it was enough. It feels a bit sad that I'll never perform this ritual again. The crooked candles exist no more. I have candles now, but they sit in small mason jars and smell of things other than wax. I light them with a kitchen lighter. It's funny how the things you vividly remember felt so insignificant at the time. I wonder if I'll remember anything from today a decade from now.

<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/0c6z0CQLmIAEOCfhNvh3n3?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>