---
title: You Fall to Your Systems
date: 2023-11-24 10:51:10
categories:
  - habits
--- 

James Clear, the author of "Atomic Habits," has a quote: "You do not rise to the level of your goals. You fall to the level of your systems."

I experienced this just today. I completed a five-day hiking trip through the Mojave Desert in Joshua Tree National Park. It was difficult, tiring, exhilarating, and rewarding - everything you'd expect. On the long walks, I brainstormed ways to improve my life, made many plans for the future, and ended up feeling very optimistic.

However, when the trip ended, I just crashed. Surprisingly, I was not mentally or physically exhausted and needed no time to recover. But I had lost my "systems." During the hikes, I woke up, had breakfast, drove to the trailheads, hiked, returned to the campsite, had dinner, and went to bed. This routine was my daily pattern. Suddenly, I needed to *decide* what to do next, and I couldn't do it effectively. I ended up wasting an entire day watching meaningless videos.

"You do not rise to the level of your goals. You fall to the level of your systems."

To maintain the mental state I achieved during the trip and act on any of the ideas I had, the first thing I need to do is develop good "systems," i.e., habits and routines. These need to be simple and maintainable.

My first goal, which is more of a habit, is to **wake up every day at 6 a.m.**, no matter what. If I go to bed late, too bad for me. I will also try to avoid drinking coffee, taking naps during the day, and consuming alcohol. The latter are not difficult as long as I can stick to the first one.

If possible, I'd also like to go for a run, walk, or bike ride as soon as I wake up. When I was hiking, one thing I loved was waking up to the fresh, cold morning air. I suspect it set an uplifting tone for the rest of the day.

