---
title: Multiple Games
date: 2023-12-14 09:41:16
categories:
  - self
  - mindfulness
---

My work requires a lot of concentration. I was good at school because I could focus my mind on specific tasks and immerse myself in them. This ability is, of course, a great skill to have today, with human progress relying on our capacity to concentrate like this.

However, life doesn't operate in the same way. You're playing multiple games at the same time - work, relationships, health, money, career - and you need to be able to switch back and forth between them as necessary. Each of these games has its own rules and requires different skill sets. Still, being able to focus on one game at a time is essential for success in them.

A meta-skill you need to develop in life is the ability to 1) quickly switch tasks, and 2) once switched, devote yourself wholeheartedly to them. This includes adjusting your emotional state. You might be completely stressed at work, but as soon as you switch to playing the relationships game, you need to load the relevant state into your working memory and stash the work-related state away for later recall.

This is both a good and a bad thing. The bad part is, of course, that you need to acquire this new meta-skill of fast context switching and come up with some organizational principle to manage the data from multiple games. The good parts are more subtle. Often, the negative emotions don't survive the recall. Unless you're having a streak of bad luck, you might be doing well in at least one game. Whenever things get too overwhelming in another game, you can switch to this one, even if only momentarily.
