---
title: Pre-Planning
date: 2023-12-06 14:05:50
categories:
  - self
  - shortcomings
---

There are two habits I am very serious about developing:

1. Regulating my sleep – going to bed early and waking up early.
2. Planning ahead of time.

I know people who prepare their entire courses during breaks and then just teach during the semester. They have their lectures, homework, quizzes, and even announcements and emails preprogrammed and just focus on execution during the semester. Pedagogically, I do not favor this approach as I teach better when I improvise during the semester and adapt to my students' needs.

However, I can no longer sustain improvisation. This semester, I'm teaching just one course on a trivial subject to a small group of students, yet I am overwhelmed by the number of weekly deadlines. Soon, I will be teaching more challenging courses to a larger student body and will have numerous administrative tasks, possibly with additional research duties.

This means preplanning is no longer a luxury, but a **necessity**.

This issue also affected me during my camping trip. I knew months in advance that I would be camping at Joshua Tree National Park. I could have packed and prepared days, if not weeks, in advance. Instead, I packed at the last minute, resulting in a miserable, anxiety-filled, and sleep-deprived trip to the airport.

Now I know the *what*. I need to figure out the *how*.