---
title: Life As A Video Game
date: 2023-12-13 08:11:30
categories:
  - self
  - mindfulness
  - framing
---

Even though meditation practice is about experience and going beyond words and concepts, the right framing using the right concepts helps to get you there. I was listening to a podcast yesterday on a long drive and wasn't feeling so great, and the podcast was about the elusive state of Flow. Just as I heard it, I tried to get into a state of flow and immediately my brain turned the road into a video game. I was back inside a *Fast and Furious* game, but I was neither fast nor furious. Suddenly everything changed. I just imagined the cars in front of me as obstacles I needed to avoid to clear the level. I set my own objectives: the least number of brakes and lane changes. I managed to get myself into a state of flow on I-95!

I hope I am able to replicate this in other scenarios. I have played video games for so long that I would rather live in them than in the real world, and what I'm realizing is that I can trick my brain into forgetting the distinction between the two worlds!
