---
title: Love the process
date: 2023-11-01 13:38:38
categories:
  - mindfulness
  - philosophy
---

There are two ways of approaching any task and life in general:

- goal oriented
- process oriented

For some reason, very likely a mix of cultural and biological, the default is the first approach. You do things in order to get somewhere, to accomplish something.

One of the most important teachings of the various contemplative traditions like Buddhism, Stoicism is that in order to find any semblance of equanimity you need to take the process oriented approach - love the process. The goal is often unattainable and impractical and even when it is attained the attainment itself is momentary and fleeting and once you're done with it you're left with a hollowness and a lack of direction.

If you want to run regularly, then you cannot make your running contingent on the next marathon. Every marathon will be over sooner than you'd like. And there will inevitably be long stretches of time in your life when you won't be able to participate in any running events. If you truly want to become a runner then you should enjoy the process of running for its own sake. You should participate in running events because you're a runner and not the other way around.

The book "Atomic Habits" has a very good way of putting this - instead of saying that you want to run, you phrase it as you want to become a runner. Instead of saying that you want to read x number of books each year, you say that you want to become an avid reader. This moves the focus from the goal to the process itself.

You can extend this to the broader extent of life. You cannot decide to work hard because you want to accomplish certain goals. Rather you're able to accomplish your goals in life because you're a hard working person. The arrow of causality points in the other direction.




