---
title: William James - Very Bad Wizards
date: 2023-11-04 14:11:35
categories:
  - habits
  - podcast
---

I'm putting this post here mainly as a bookmark to myself. 
Sam Harris mentioned this podcast in one of his discussions and so I had a listen.

I don't remember much about it's content but I remember thinking just how much William James already knew about psychology and how well he understood the the human mind to make all these claims without doing any scientific research. Of course, he must have read several religious and philosophical texts of his time and infered based on them. But to synthesize something so precise and practical from these abstract and often incorrect sources is nothing short of genius. Having never done any experiments, his claims cannot be called scientific or even emperical, nevertheless as works of fiction and philosophy they contain great ideas that we can investigate today using the scientific method.

My recollection is that in his thesis James concludes that the human society relies entirely on habits and that there is no greater endeavor than to develop good habits. 
He even lays out some suggestions as to how to go about doing this.
I couldn't agree more.

I will listen to this episode again and take notes.