---
title: Casey Neistat
date: 2023-10-30 20:59:31
categories: 
  - habits
---

I try to stay away from the internet meme culture as much as possible. 
I no longer find it funny to make fun of people unintentionally (I do still love absurd humor and find many of the controversial comics funny).

I saw a Casey Neistat thumbnail on Nerdwriter1's channel but I stayed away from it thinking that he's just another internet meme personality. 

But for some reason, I watched one video of Neistat and got hooked. I immediately realized that this wasn't another internet troll but a master at his craft. 

I love that when I open his videos, most of the time I do not know what's going to happen. And yet, I'm somehow convinced that the video is going to go well! Behind his "bro" facade he is a master storyteller. Rather, his "bro" facade is part of his storytelling act. 

I also love his cinematography, editing, music mixing, just everything. Never a boring video. 

I'm writing all this because I learned about his work ethic and feel very inspired by it.
For quite some time now, I have been struggling with my sleep and work routine. 
I'm slowly improving but as I'm writing this I'm realizing that I lack role models in this area.
The people in my life either don't do work they like or work hard obsessively for the sake or working hard. 
But now I have Neistat! He is someone whose work and skill I admire and understand and whose work ethic I hope to emulate. 

I hope that this is the kick I needed to pull myself up by the bootstraps.
Of course, I feel very motivated and inspired *now* but the real test is whether this is going to last. Only time will tell.

<iframe width="560" height="315" src="https://www.youtube.com/embed/C-Cvl3_CH2A?si=RW4KEK-zT6Y3olaE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>