---
title: Setting intention
date: 2023-12-07 10:39:27
categories:
  - meditation
  - mindfulness
---

One of the best "hacks" for being mindful and present is to set intentions before starting any task. This includes tasks like planning and concentrated thinking. You just "let your brain know" that this is what it needs to be doing now and it can return to other tasks afterward.

This aligns with the analogy that the brain is a blind automaton with different parts working in parallel. There is communication between the various parts, but this communication is often delayed and imperfect. By setting intentions, you are sending a strong message from one part of the brain to another.

Like right now, there is a lot of chaos happening around me. My internet is down, and I'm supposed to be in a meeting. I have a bunch of deadlines today and I need to get back to planning several things soon. If I just let my mind wander, it will keep jumping from one task to another without actually resolving anything, just increasing my anxiety. Instead, I have decided, as much as possible, that this is my writing time. I do still get thoughts about other things and keep a notebook with me to jot them down to return to them after I'm done. But having this clear intention of writing is essential for me to make it to the end of this sentence with full commitment.