---
title: Saying No
date: 2023-11-27 07:59:36
categories:
  - podcast
  - oliver burkeman
  - waking up
---
In a podcast episode on waking up, Oliver Burkeman talks about the necessity to say no to certain things in life because you only have a finite amount of time. This becomes clear when you do the calculation involving the time available and the time required to get things done. This is further emphasized by the fact that we don't always have the will, energy, or capacity to do the things we would like to do.

Two things that have been helpful to me:
- You have to learn to say no to things that you *want to do*. Just yesterday, I was at a yoga class which was overcrowded. I usually love staying for the final resting pose but I knew that if I stayed until the end, it would take me forever to leave. So, reluctantly, I left early. I still got most of the benefits of the class and managed to leave on time by making a small sacrifice.
- There is a difference between conceptually understanding something and experientially understanding it. The effect a concept has on your life is much greater once you've internalized it. Even though it's *obvious* that you have to say no to things, we don't always do it. And even when we do, we tend to feel guilty or irritated about it. One has to realize that there is just no alternative. This is a consequence of our finiteness that we need to accept and move on.