---
title: Being Present
date: 2023-12-07 10:00:47
categories:
  - mindfulness
  - meditation
---

"Be Here Now," the classic book by Ram Dass, is supposed to encapsulate the project of meditation. The more I struggle with meditation, the more I realize how central this principle is to the practice.

My brain is constantly future-looking, sometimes in small ways - I might be brewing coffee and simultaneously thinking about the joy of drinking it afterwards, or I might be biking to work while thinking of what I'm going to do in class today - and sometimes in large ways - I might be doing something mundane like laundry while worrying about my career and long-term future. We are genetically, culturally, and habitually in this constant state of chasing the future.

Why is this bad? Because it represents habituation and a lack of intention. One of the goals of mindfulness is the recognition of conditioning and intentionally choosing to either do something or not. Of course, future planning is a good thing, but it does not need to be done constantly. You need to decide to plan for the future, take care of it, and then let go and return to the present.

It is, of course, easier said than done. I am not sure if it is even possible to be fully present in the current moment. But mindfulness teachings come to the rescue again - the goal is never the reason to do something; the process is. You need to enjoy this process of recognizing that the mind is future-looking and decide if this is where you want it to be. Whether you want it or not, you just make a decision and let go.