---
title: Minimal Setting
date: 2023-12-12 14:17:29
categories:
  - consciousness
  - letting-go
---

I have a theory about what meditation practice aims to achieve by urging us to "let go".
I believe consciousness or awareness is the bare minimum state of mind required to function. 
It's like the OS kernel (or is the BIOS) that loads when your computer starts, before any other program is loaded in working memory.
It's the smallest piece of software necessary to indicate that your mind has booted up.

In our normal existence, we run several other processes on top of it - with thinking being the most energy-consuming one.
But we are also engaged in seeing, listening, reading, parsing, talking, etc.
There are times when thinking is essential - after all, it's the foundation of all modern civilization.
However, most of the time, we run this program unintentionally.
It becomes a runaway program that spawns many threads, each consuming significant resources - like when you have too many tabs open in your web browser.

The goal of meditation is to recognize these redundant threads and shut them down as necessary.
It involves realizing that most of the time, you don't need to load anything other than your OS, and just allow the processor to relax and cool down.
Of course, you occasionally need several threads, and then the processor needs to shift into intensive thinking mode, but this shouldn't be the default state.

This approach is akin to opening a task manager on your computer, deciding which threads are necessary, and terminating the unnecessary ones.
I believe this leads to optimized brain function, declutters its RAM, and allows the brain to use its resources for more significant subconscious tasks.